# Generated by Django 5.1.6 on 2025-03-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acgroup_id', models.IntegerField(blank=True, null=True)),
                ('acgroup_name', models.CharField(blank=True, max_length=6, null=True)),
                ('acgroup_holidayvalid', models.IntegerField(blank=True, null=True)),
                ('acgroup_verifystytle', models.IntegerField(blank=True, null=True)),
                ('timezone1', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone2', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone3', models.CharField(blank=True, max_length=50, null=True)),
                ('terminal_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ac_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcHolidaysetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('holiday_id', models.CharField(blank=True, max_length=50, null=True)),
                ('holiday_name', models.CharField(blank=True, max_length=100, null=True)),
                ('holiday_start', models.DateField(blank=True, null=True)),
                ('holiday_end', models.DateField(blank=True, null=True)),
                ('actimezoneid', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ac_holidaysetting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcTimezone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timezone_id', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone_name', models.CharField(blank=True, max_length=255, null=True)),
                ('timezone_sunstart', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone_sunend', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone_monstart', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone_monend', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone_tuesstart', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone_tuesend', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone_wedstart', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone_wedend', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone_thursstart', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone_thursend', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone_fristart', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone_friend', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone_satstart', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone_satend', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ac_timezone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttShift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('max_entry_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('work_hours', models.IntegerField(blank=True, null=True)),
                ('break_type', models.CharField(choices=[('Sin descanso', 'Sin descanso'), ('Descanso libre', 'Descanso libre')], default='Sin descanso', max_length=20)),
                ('break_minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
            options={
                'db_table': 'att_shift',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrDepartment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_code', models.IntegerField(blank=True, null=True)),
                ('dept_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'hr_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrEmployee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_pin', models.BigIntegerField(unique=True)),
                ('emp_ssn', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_role', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_username', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_pwd', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('emp_privilege', models.IntegerField(blank=True, null=True)),
                ('emp_hiredate', models.DateField(blank=True, null=True)),
                ('emp_firedate', models.DateField(blank=True, null=True)),
                ('emp_birthday', models.DateField(blank=True, null=True)),
                ('emp_active', models.BooleanField(default=True)),
                ('emp_address', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_operationmode', models.IntegerField(blank=True, null=True)),
                ('emp_gender', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_employee',
                'managed': False,
            },
        ),
    ]
