# Generated by Django 5.1.6 on 2025-06-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_gruposupervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadoturno',
            name='aprobado_jefe_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empleadoturno',
            name='aprobado_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
