# Generated by Django 5.1.6 on 2025-03-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20250321_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpCostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'emp_cost_center',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'emp_job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpleadoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('horas_extra', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('aprobado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'empleado_turno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'emp_role',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='hrgroup',
            options={'managed': False},
        ),
    ]
