# Generated by Django 5.1.6 on 2025-06-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_empleadoturno_aprobado_jefe_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_id', models.IntegerField()),
                ('vista', models.CharField(max_length=50)),
                ('tiene_acceso', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'permiso_rol',
                'managed': False,
            },
        ),
    ]
