# Generated by Django 5.1.6 on 2025-03-28 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_empcostcenter_empjob_empleadoturno_emprole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttPunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_time', models.DateTimeField()),
                ('terminal_id', models.CharField(max_length=50)),
                ('punch_type', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='API.hremployee')),
            ],
            options={
                'verbose_name': 'Marcación',
                'verbose_name_plural': 'Marcaciones',
                'db_table': 'att_punches',
            },
        ),
    ]
