# Generated by Django 5.1.6 on 2025-06-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_aprobacionhorasextras'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrGroupJefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hrgroup_jefes_planta',
                'managed': False,
            },
        ),
    ]
